// Generated for GLFW 3.4 — EazyMake package (Windows/MSYS2)
// Normally generated by CMake; provided here for ezmk source-based compilation.
#pragma once

#define GLFW_VERSION_MAJOR 3
#define GLFW_VERSION_MINOR 4
#define GLFW_VERSION_REVISION 0

#define _GLFW_USE_CONFIG_H
#define _GLFW_WIN32
